package com.janne6565.hermes.services.auth;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.janne6565.hermes.entity.MailAccountEntity;
import com.janne6565.hermes.model.core.MailProviderType;
import com.janne6565.hermes.repository.AccountSyncStateRepository;
import com.janne6565.hermes.repository.MailAccountRepository;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InOrder;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * Disconnect deletes two rows, and the order is the whole test.
 *
 * <p>{@code account_sync_state.account_id} carries {@code ON DELETE CASCADE} (V5). Deleting the
 * account first makes Postgres cascade the cursor row away, and Hibernate's own delete of that same
 * row then finds nothing and throws {@code StaleStateException} ("expected row count 1 but was 0"),
 * rolling the transaction back — the account stays connected and the UI can never let go of it.
 *
 * <p>The assertion lives in a mock-ordering test rather than a JPA one because the H2 schema used
 * by the test profile is generated by Hibernate with Flyway disabled, so it has no {@code ON DELETE
 * CASCADE} and cannot reproduce the failure at all.
 */
@ExtendWith(MockitoExtension.class)
class MailAccountServiceDisconnectTest {

    @Mock private MailAccountRepository accountRepository;
    @Mock private AccountSyncStateRepository syncStateRepository;
    @Mock private TokenCipher tokenCipher;

    private MailAccountService service;

    private final UUID accountId = UUID.fromString("0535e656-7386-418e-a15f-bd4c16006cf7");

    @BeforeEach
    void setUp() {
        service =
                new MailAccountService(
                        accountRepository,
                        syncStateRepository,
                        tokenCipher,
                        Clock.fixed(Instant.parse("2026-08-17T00:00:00Z"), ZoneOffset.UTC));
    }

    @Test
    void deletesTheCursorRowBeforeTheAccountItHangsOff() {
        MailAccountEntity account =
                MailAccountEntity.builder()
                        .provider(MailProviderType.GMAIL)
                        .email("reader@example.com")
                        .build();
        account.setId(accountId);
        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));

        service.disconnect(accountId);

        InOrder inOrder = Mockito.inOrder(syncStateRepository, accountRepository);
        inOrder.verify(syncStateRepository).deleteById(accountId);
        // Flushed while the parent is still there, so the statement the database sees is the one
        // Hibernate expects to match a row.
        inOrder.verify(syncStateRepository).flush();
        inOrder.verify(accountRepository).delete(account);
    }

    @Test
    void unknownAccountDeletesNothing() {
        when(accountRepository.findById(accountId)).thenReturn(Optional.empty());

        service.disconnect(accountId);

        verify(accountRepository).findById(accountId);
        verifyNoInteractions(syncStateRepository);
    }
}
